name: Top GitHub Users
on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'
jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16
      - uses: uwenayoallain/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
